# v.2.0
name: Pull action
on: [pull_request]
jobs:
  pull-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    #  - uses: actions/setup-node@v2
    #    with:
    #       node-version: '11.2.0'
      - name: articles-management
        working-directory: ./services/articles-management/
        run: |
          npm install -g jest
          npm install eslint -DE
          npm run lint
          npm test 
     # - name: authentication
     ## manglar testar
     #   working-directory: ./services/authentication/

      - name: events-management
        working-directory: ./services/events-management/
        run: |
          npm install -g jest
          npm install eslint -DE
          npm run lint
          npm test
      - name: user-management
        working-directory: ./services/user-management
        run: |
          npm install -g jest
          npm install eslint -DE
          npm run lint
          npm test 
      - name: notification
        working-directory: ./services/notification
        run: |
          npm install -g jest
          npm install eslint -DE
          npm run lint
          npm test
  #    - uses: artiomtr/jest-coverage-report-action@v2.0-rc.5
  #     with:
  #        working-directory: ./services
  #        github-token: ${{ secrets.GITHUB_TOKEN }}
