# v.2.0
# finne ut korleis konsumere rapportane. Definere standard directory i repo kanskje? 
# bruke artiomtr/jest-coverage-report-action@v2.0-rc.5 for jest rapport uthenting? 

name: Pull action
on: [pull_request]
jobs:
  pull-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    #  - uses: actions/setup-node@v2
    #    with:
    #       node-version: '11.2.0'
      - name: articles-management
        working-directory: ./services/articles-management/
        run: |
          npm install -g jest
          npm install eslint -DE
          npm run lint
          npm test 
     # - name: authentication
     ## manglar testar
     #   working-directory: ./services/authentication/
      - name: archive pull action artifacts
        uses: actions/upload-artifact@v3
        with:
          name: services-articles-management
          path: local/docker/reports/
      
      - name: index.html of coverage results
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: local/docker/reports/lcov-report/index.html   

      - name: events-management
        working-directory: ./services/events-management/
        run: |
          npm install -g jest
          npm install eslint -DE
          npm run lint
          npm test
      - name: user-management
        working-directory: ./services/user-management
        run: |
          npm install -g jest
          npm install eslint -DE
          npm run lint
          npm test 
      - name: notification
        working-directory: ./services/notification
        run: |
          npm install -g jest
          npm install eslint -DE
          npm run lint
          npm test
    # test ut action frå marketplace for terminering av workflow ved failure
      - uses: vishnudxb/cancel-workflow@v1.2
        with:
          if: failure()
          workflow_id: ${{ github.run_id }}
          access_token: ${{ github.token }}
  #    - uses: artiomtr/jest-coverage-report-action@v2.0-rc.5
  #     with:
  #        working-directory: ./services
  #        github-token: ${{ secrets.GITHUB_TOKEN }}
